SELECT * FROM JAVASQL

-- [ALT] + [X]

CREATE TABLE JAVASQL1(
	TEST3 NVARCHAR2(10),
	TEST4 NVARCHAR2(10)
	)
	
SELECT * FROM JAVASQL1

-- NAVER테이블
-- 아이디, 비밀번호, 이름, 나이, 성별, 이메일, 연락처
-- 아이디를 PK로 지정하기

DROP TABLE NAVER
CREATE TABLE NAVER(
	ID 		 NVARCHAR2(20),
	PASSWORD NVARCHAR2(10),
	NAME  	 NVARCHAR2(10),
	AGE 	 NUMBER	,
	GENDER   NVARCHAR2(10),
	PHONE    NVARCHAR2(20),
	CONSTRAINT NA_ID_PK PRIMARY KEY(ID)
)

SELECT * FROM NAVER

INSERT 
INTO NAVER VALUES('MUMUM', '1234', '문혁준', 29, '남', '010-4005-3521')